import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('{{project_name.titleCase()}}')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Welcome 👋',
              style: TextStyle(fontSize: 24),
            ),
            const SizedBox(height: 8),
            const Text('This project was generated by Geneser.'),
            const SizedBox(height: 24),
            FilledButton.icon(
              onPressed: () => context.go('/about'),
              icon: const Icon(Icons.info_outline),
              label: const Text('Learn more'),
            ),
          ],
        ),
      ),
    );
  }
}
