import 'package:flutter/material.dart';
class AppColors extends ThemeExtension<AppColors> {
  final Color primary; final Color onPrimary; final Color background; final Color onBackground; final Color surface; final Color onSurface; final Color error; final Color grey1; final Color grey2; final Color grey3;
  const AppColors({required this.primary, required this.onPrimary, required this.background, required this.onBackground, required this.surface, required this.onSurface, required this.error, required this.grey1, required this.grey2, required this.grey3});
  factory AppColors.light() => const AppColors(primary: Color({{primary_color}}), onPrimary: Color(0xFFFFFFFF), background: Color(0xFFFFFFFF), onBackground: Color(0xFF263238), surface: Color(0xFFFAFAFA), onSurface: Color(0xFF263238), error: Color(0xFFB00020), grey1: Color(0xFFBEC1C3), grey2: Color(0xFF7D8488), grey3: Color(0xFF263238));
  factory AppColors.dark() => const AppColors(primary: Color({{primary_color}}), onPrimary: Color(0xFFFFFFFF), background: Color(0xFF0A0A0A), onBackground: Color(0xFFFAFAFA), surface: Color(0xFF161616), onSurface: Color(0xFFFFFFFF), error: Color(0xFFCF6679), grey1: Color(0xFF263238), grey2: Color(0xFF7D8488), grey3: Color(0xFFBEC1C3));
  @override ThemeExtension<AppColors> copyWith({Color? primary, Color? onPrimary, Color? background, Color? onBackground, Color? surface, Color? onSurface, Color? error, Color? grey1, Color? grey2, Color? grey3}) => AppColors(primary: primary ?? this.primary, onPrimary: onPrimary ?? this.onPrimary, background: background ?? this.background, onBackground: onBackground ?? this.onBackground, surface: surface ?? this.surface, onSurface: onSurface ?? this.onSurface, error: error ?? this.error, grey1: grey1 ?? this.grey1, grey2: grey2 ?? this.grey2, grey3: grey3 ?? this.grey3);
  @override ThemeExtension<AppColors> lerp(ThemeExtension<AppColors>? o, double t) { if (o is! AppColors) return this; return AppColors(primary: Color.lerp(primary, o.primary, t)!, onPrimary: Color.lerp(onPrimary, o.onPrimary, t)!, background: Color.lerp(background, o.background, t)!, onBackground: Color.lerp(onBackground, o.onBackground, t)!, surface: Color.lerp(surface, o.surface, t)!, onSurface: Color.lerp(onSurface, o.onSurface, t)!, error: Color.lerp(error, o.error, t)!, grey1: Color.lerp(grey1, o.grey1, t)!, grey2: Color.lerp(grey2, o.grey2, t)!, grey3: Color.lerp(grey3, o.grey3, t)!); }
}
